const GET_LISTS = 'GET_LISTS';
const UPDATE_LIST = 'UPDATE_LIST';
const DELETE_LIST = 'DELETE_LIST';
const CREATE_LIST = 'CREATE_LIST';

// INFO: TASKS
const ADD_LIST_TASK = 'ADD_LIST_TASK';
const EDIT_LIST_TASK = 'EDIT_LIST_TASK';
const DELETE_LIST_TASK = 'DELETE_LIST_TASK';
const UPDATE_TASK_LIST = 'UPDATE_TASK_LIST';

export {
    GET_LISTS,
    UPDATE_LIST,
    DELETE_LIST,
    CREATE_LIST,
    ADD_LIST_TASK,
    EDIT_LIST_TASK,
    DELETE_LIST_TASK,
    UPDATE_TASK_LIST,
};
